"""Debug: See actual trades generated by backtest"""
import asyncio
import logging
from datetime import datetime, timedelta

logging.basicConfig(level=logging.WARNING)

async def main():
    from backtesting.engine import BacktestEngine
    from backtesting.templates import get_template
    from backtesting.builder import strategy_builder
    
    print("\n" + "="*80)
    print("BACKTEST TRADE DETAILS")
    print("="*80)
    
    strategy_def = get_template('rsi_oversold')
    strategy_func = strategy_builder.build_strategy(strategy_def)
    
    end_date = datetime.now()
    start_date = end_date - timedelta(days=730)  # 2 years
    
    engine = BacktestEngine()
    results = await engine.run_backtest(
        symbol='NVDA',
        start_date=start_date.strftime('%Y-%m-%d'),
        end_date=end_date.strftime('%Y-%m-%d'),
        strategy_fn=strategy_func,
        initial_capital=100000
    )
    
    print(f"\nTotal Trades: {results['num_trades']}")
    print(f"Win Rate: {results['win_rate']:.1%}")
    print(f"Total Return: {results['total_return']:.2f}")
    print(f"Total Return %: {results['total_return_pct']:.4%}")
    
    if results['trades']:
        print("\n" + "-"*80)
        print("INDIVIDUAL TRADES:")
        print("-"*80)
        
        for i, trade in enumerate(results['trades'][:10], 1):
            print(f"\nTrade {i}:")
            print(f"  Entry:  ${trade['entry_price']:.2f} on {trade['entry_date'][:10]}")
            print(f"  Exit:   ${trade['exit_price']:.2f} on {trade['exit_date'][:10]}")
            print(f"  Stop:   ${trade['stop']:.2f}")
            print(f"  Target: ${trade['target']:.2f}")
            print(f"  P&L:    ${trade['pnl']:.2f} ({trade['pnl_pct']:+.2%})")
            print(f"  Result: {trade['outcome'].upper()}")
    
    print("\n" + "="*80)

if __name__ == "__main__":
    asyncio.run(main())


